[project]
name = "gpu-programming-for-ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cupy-cuda13x>=13.6.0",
    "jupyter>=1.1.1",
    "numba>=0.60.0",
    "numpy>=2.0.2",
    "torch>=2.8.0",
]
